version: 1.0.{build}
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  auth_token:
    secure: hDS4v/d2PaQhhyTJVBj9Qg==
  channel: Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true